import {randomBytes,randomUUID,scrypt as scryptCallback,timingSafeEqual,createHash} from 'node:crypto';
import {promisify} from 'node:util';
import STORES from './stores.mjs';
const scrypt=promisify(scryptCallback);
const ACCOUNTS=[['achicale','André Chicale','regional'],['dkoch','Diego Koch','regional'],['eoliveira','Evelin de Oliveira','regional'],['fpazini','Fabiano Pazini','regional'],['jose.gilvan','José Gilvan','regional'],['lais','Laís Andrioli','regional'],['lalves','Lisiane Alves','regional'],['etagaki','Ricardo Etagaki','regional'],['rsousa','Roseli Teixeira','regional'],['famorim','Francisco Amorim','director'],['stephanie.silva','Stephanie Silva','test']];
const ALIASES={'Fabiano':'Fabiano Pazini','Roseli':'Roseli Teixeira','Lisiane':'Lisiane Alves','Etagaki':'Ricardo Etagaki','Lais':'Laís Andrioli','Gilvan':'José Gilvan','Evelin':'Evelin de Oliveira','Diretor de Operações':'Francisco Amorim'};
const hash=s=>createHash('sha256').update(s).digest('hex');
const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const fail=(status,message)=>{const e=new Error(message);e.status=status;throw e};
function equal(a,b){if(typeof a!=='string'||typeof b!=='string')return false;const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y)}
export async function passwordHash(password){const salt=randomBytes(16).toString('hex');const value=await scrypt(password,salt,32,{N:2**17,r:8,p:1,maxmem:192*1024*1024});return `scrypt$${salt}$${value.toString('hex')}`}
async function validPassword(password,encoded){if(typeof password!=='string'||password.length>256)return false;try{const [method,salt,expected]=encoded.split('$');if(method!=='scrypt')return false;const value=await scrypt(password,salt,32,{N:2**17,r:8,p:1,maxmem:192*1024*1024});return equal(value.toString('hex'),expected)}catch{return false}}
function userPublic(u){return {id:u.username,username:u.username,email:u.email,name:u.name,role:u.role,mustChange:u.mustChange}}
const storesFor=u=>u.role==='regional'?STORES.filter(s=>s.regional===u.name):STORES;
function cookie(token,clear=false){return `visitas_session=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${clear?0:43200}`}
function values(v,u){const {code,date,note=''}=v;if(typeof code!=='string'||!storesFor(u).some(s=>s.code===code))fail(403,'Você não tem acesso a esta loja.');if(typeof date!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(Date.parse(date+'T12:00:00Z'))||new Date(date+'T12:00:00Z').toISOString().slice(0,10)!==date||date>today())fail(400,'Informe uma data válida, até hoje.');if(typeof note!=='string'||note.length>500)fail(400,'Observação deve ter até 500 caracteres.');return {code,date,note:note.trim()}}
function reasonValues(v){const reason=v.reason,note=v.note??'';if(!['Marcação indevida','Outro'].includes(reason)||typeof note!=='string'||note.length>500||(reason==='Outro'&&!note.trim()))fail(400,'Informe a justificativa da exclusão.');return {deletedReason:reason,deletedNote:reason==='Outro'?note.trim():''}}
async function allKeys(store,prefix){const {blobs}=await store.list({prefix});return blobs.map(b=>b.key)}
async function mapLimited(items,fn){const result=[];for(let i=0;i<items.length;i+=15)result.push(...await Promise.all(items.slice(i,i+15).map(fn)));return result}
// Each visit and each deletion is its own immutable object; concurrent visits never overwrite an array.
async function writeNew(store,key,value){const result=await store.setJSON(key,value,{onlyIfNew:true});if(!result.modified)return false;const saved=await store.get(key,{type:'json'});if(JSON.stringify(saved)!==JSON.stringify(value))fail(503,'Não foi possível confirmar o salvamento. Tente novamente.');return true}
async function makeSession(store,user){const token=randomBytes(32).toString('hex'),csrf=randomBytes(32).toString('hex');await writeNew(store,'sessions/'+hash(token),{user:user.username,version:user.version,csrf,expires:Date.now()+43200000});return {token,csrf}}
async function account(store,username,initial){const key='users/'+username;let entry=await store.getWithMetadata(key,{type:'json'});if(entry)return entry;const configured=ACCOUNTS.find(a=>a[0]===username);if(!configured)return null;if(typeof initial!=='string'||initial.length<10)fail(503,'A hospedagem precisa configurar a senha inicial do aplicativo.');const [id,name,role]=configured;const user={username:id,email:id+'@petzcobasi.com.br',name,role,password:await passwordHash(initial),version:randomUUID(),mustChange:true};await writeNew(store,key,user);entry=await store.getWithMetadata(key,{type:'json'});if(!entry)fail(503,'Não foi possível criar seu acesso. Tente novamente.');return entry}
async function authenticated(store,request,path){const token=(request.headers.get('cookie')||'').match(/(?:^|;\s*)visitas_session=([a-f0-9]{64})(?:;|$)/)?.[1];if(!token)fail(401,'Entre para continuar.');const session=await store.get('sessions/'+hash(token),{type:'json'});if(!session||session.expires<Date.now())fail(401,'Sua sessão expirou. Entre novamente.');const entry=await store.getWithMetadata('users/'+session.user,{type:'json'});if(!entry||entry.data.version!==session.version)fail(401,'Entre novamente com sua senha atual.');if(request.method!=='GET'&&!equal(request.headers.get('x-csrf-token'),session.csrf))fail(403,'Atualize a página e tente novamente.');if(entry.data.mustChange&&!['/api/me','/api/password','/api/logout'].includes(path))fail(403,'Defina sua senha no primeiro acesso.');return {user:entry.data,etag:entry.etag,session,sessionKey:'sessions/'+hash(token)}}
async function recentFailures(store,identifier){const bucket=Math.floor(Date.now()/900000),prefix='failures/'+hash(identifier)+'/',keys=[...await allKeys(store,prefix+bucket+'/'),...await allKeys(store,prefix+(bucket-1)+'/')];return keys.filter(k=>Number(k.split('/').at(-1).split('-')[0])>Date.now()-900000).length}
async function addFailure(store,identifier){const bucket=Math.floor(Date.now()/900000);await writeNew(store,`failures/${hash(identifier)}/${bucket}/${Date.now()}-${randomUUID()}`,{failedAt:Date.now()})}
async function visitsFor(store,user){const prefix='visits/'+user.username+'/',keys=await allKeys(store,prefix),raw=await mapLimited(keys,key=>store.get(key,{type:'json'}));return mapLimited(raw.filter(Boolean),async v=>{const deletion=await store.get('deleted/'+user.username+'/'+v.id,{type:'json'});return {...v,...(deletion||{}),author:user.role==='regional'?'Regional '+user.name:user.name}})}
export function createHandler(getStore,env={}){return async function handle(request,context={}){const headers=new Headers({'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin'});try{const url=new URL(request.url),path=url.pathname;if(!['GET','POST'].includes(request.method))fail(405,'Método não permitido.');if(env.CONTEXT&&env.CONTEXT!=='production'&&env.CONTEXT!=='dev')fail(503,'Use o endereço principal publicado do aplicativo.');let body={};if(request.method==='POST'){const origin=request.headers.get('origin');if(origin&&origin!==url.origin)fail(403,'Origem inválida.');if(!request.headers.get('content-type')?.startsWith('application/json'))fail(415,'Formato inválido.');const raw=await request.text();if(raw.length>2000000)fail(413,'Envio muito grande.');try{body=JSON.parse(raw);if(!body||Array.isArray(body)||typeof body!=='object')throw Error()}catch{fail(400,'Dados inválidos.')}}const store=getStore({name:'visitas-cobasi-v1',consistency:'strong'});let output;
if(path==='/api/login'&&request.method==='POST'){const {login,password}=body;if(typeof login!=='string'||login.length>254||typeof password!=='string'||password.length>256)fail(400,'Informe seu usuário/e-mail e senha.');const identifier=login.trim().toLowerCase(),username=identifier.endsWith('@petzcobasi.com.br')?identifier.slice(0,-'@petzcobasi.com.br'.length):identifier,ip='ip:'+(context.ip||'unknown');if(await recentFailures(store,ip)>=40)fail(429,'Muitas tentativas. Aguarde 15 minutos.');const known=ACCOUNTS.some(a=>a[0]===username);if(known&&await recentFailures(store,'user:'+username)>=8)fail(429,'Muitas tentativas. Aguarde 15 minutos.');const entry=known?await account(store,username,env.INITIAL_PASSWORD):null;const dummy='scrypt$'+('0'.repeat(32))+'$'+('0'.repeat(64));if(!await validPassword(password,entry?.data.password||dummy)){await addFailure(store,ip);if(known)await addFailure(store,'user:'+username);fail(401,'Usuário/e-mail ou senha incorretos.')}const user=entry.data,{token,csrf}=await makeSession(store,user);headers.set('Set-Cookie',cookie(token));output={user:userPublic(user),csrf};
}else{const auth=await authenticated(store,request,path),{user,session}=auth;if(path==='/api/me'&&request.method==='GET')output={user:userPublic(user),csrf:session.csrf};
else if(path==='/api/password'&&request.method==='POST'){const {password,confirmation}=body;if(typeof password!=='string'||password.length<10||password.length>128||!password.trim())fail(400,'Use uma senha entre 10 e 128 caracteres.');if(password!==confirmation)fail(400,'As senhas não coincidem.');if(password===env.INITIAL_PASSWORD||await validPassword(password,user.password))fail(400,'Escolha uma senha diferente da senha atual e da inicial.');if(!user.mustChange&&!await validPassword(body.currentPassword,user.password))fail(401,'A senha atual está incorreta.');const updated={...user,password:await passwordHash(password),version:randomUUID(),mustChange:false};const write=await store.setJSON('users/'+user.username,updated,{onlyIfMatch:auth.etag});if(!write.modified)fail(409,'Seu acesso mudou em outra sessão. Entre novamente.');const check=await store.get('users/'+user.username,{type:'json'});if(check?.version!==updated.version)fail(409,'Atualize e entre novamente com a nova senha.');const {token,csrf}=await makeSession(store,updated);headers.set('Set-Cookie',cookie(token));output={user:userPublic(updated),csrf};}
else if(path==='/api/logout'&&request.method==='POST'){await store.delete(auth.sessionKey);headers.set('Set-Cookie',cookie('',true));output={ok:true};}
else if(path==='/api/data'&&request.method==='GET')output={stores:storesFor(user),visits:await visitsFor(store,user)};
else if(path==='/api/permissions'&&request.method==='GET'){const allowed=user.role==='regional'?ACCOUNTS.filter(a=>a[0]===user.username):ACCOUNTS;output={users:allowed.map(([username,name,role])=>({username,email:username+'@petzcobasi.com.br',name,role,visitAccess:'Somente visitas do próprio usuário',stores:storesFor({name,role})}))};}
else if(path==='/api/visits'&&request.method==='POST'){const v={...values(body,user),id:randomUUID(),createdAt:new Date().toISOString()};await writeNew(store,'visits/'+user.username+'/'+v.id,v);output={ok:true,id:v.id};}
else if(path==='/api/visits/delete'&&request.method==='POST'){const {id}=body;if(typeof id!=='string'||!/^[a-f0-9-]{36,64}$/.test(id))fail(400,'Visita inválida.');const visit=await store.get('visits/'+user.username+'/'+id,{type:'json'});if(!visit)fail(404,'Visita não encontrada para seu usuário.');const deletion={...reasonValues(body),deletedAt:new Date().toISOString(),deletedBy:user.name};if(!await writeNew(store,'deleted/'+user.username+'/'+id,deletion))fail(409,'Esta visita já está em Excluídos.');output={ok:true};}
else if(path==='/api/import'&&request.method==='POST'){if(!Array.isArray(body.visits)||body.visits.length>1000)fail(400,'Importe no máximo 1000 visitas por envio.');let count=0;const planned=[];for(const v of body.visits){if(!v||typeof v!=='object')fail(400,'Histórico inválido.');const name=String(v.author||'').replace(/^Regional /,'');if((ALIASES[name]||name)!==user.name)continue;const clean=values(v,user),source=String(v.id||JSON.stringify([v.code,v.date,v.note,v.author,v.deletedAt])),id=hash('legacy:'+source);let deletion=null;if(v.deletedAt){if(typeof v.deletedAt!=='string'||!Number.isFinite(Date.parse(v.deletedAt)))fail(400,'Data de exclusão inválida.');deletion={...reasonValues({reason:v.deletedReason,note:v.deletedNote||''}),deletedAt:v.deletedAt,deletedBy:user.name}}planned.push({id,clean,deletion})}for(const {id,clean,deletion} of planned){if(deletion)await writeNew(store,'deleted/'+user.username+'/'+id,deletion);if(await writeNew(store,'visits/'+user.username+'/'+id,{...clean,id,createdAt:new Date().toISOString()}))count++}output={ok:true,imported:count};}
else fail(404,'Página não encontrada.');}
return new Response(JSON.stringify(output),{status:200,headers});}catch(error){const status=error.status||503;if(!error.status)console.error('API failure:',error.name);return new Response(JSON.stringify({error:error.status?error.message:'Não foi possível acessar o armazenamento online. Confira a configuração da Netlify e tente novamente.'}),{status,headers})}}}
